---
iconicmaps/tu1: "https://www.theminecraftarchitect.com/tutorial-worlds/tu1"
iconicmaps/dropper: "https://www.planetminecraft.com/project/advpuzz-the-dropper-2-new-levels/"

tp/henriiPackV1: "https://github.com/HenriiTV/texturepacks/blob/main/henriiPackV1.zip"
tp/1-8-purple-pvp: "https://github.com/HenriiTV/texturepacks/blob/main/1.8-purple_pvp.zip"
